import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { ModalProvider, useModal } from "@/context/ModalContext";
import ModalRootClient from "./ModalRootClient";

export const metadata: Metadata = {
  title: "Here*",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          <ModalRootClient>
            <div className="min-h-screen flex flex-col justify-between gap-8">
              <main className="flex flex-col justify-center">{children}</main>
              <Footer />
            </div>
          </ModalRootClient>
        </ModalProvider>
      </body>
    </html>
  );
}
